### ISSUE TITLE
Nothing happens when sending out tweet

### ISSUE THREAD

**Issue by kenjibailly** [chhoumann/notetweet_obsidian#22]
Plugin is connected to twitter.

Although I think I might have done something wrong in the twitter developer portal as it doesn't match the video anymore.
To enable read and write permissions I need to enable authentication. where it requires to add a callback URI/redirect URL and Website URL.

I didn't know what to put there so I put twitter.com twice there.
But this might be wrong.

![image](https://user-images.githubusercontent.com/9883910/149265404-7338593f-7804-4f94-b9a1-71cffd8f34ae.png)

**Comment by chhoumann** [comment]
Hey @kenjibailly!

Are you scheduling tweets, or are you just trying to post directly from Obsidian?

If you're just trying to post directly, I believe you should use a Standalone app, rather than an elevated app. Just click Overview under the Project & Apps header in the sidebar. At the bottom of the overview page, you should be able to create a standalone app and get the correct keys.

**Comment by kenjibailly** [comment]
Right now I'm just trying to post directrly from Obsidian.
I don't find where I can create a standalone app. I also do not have access to elevated apps as there is a button "Apply for Elevetaed".
I have no "Overview" under my projects and apps. Just my project and my app in there. Besides that there isn't much to see.
Let me send you a few screenshots if that helps.

![image](https://user-images.githubusercontent.com/9883910/149407553-c7df0f6e-88da-47f7-99e5-6875739af469.png)
![2022_01_13_21_53_54_Twitter_Developers_Brave](https://user-images.githubusercontent.com/9883910/149407710-a38fc1bb-5edc-411d-b578-b53f84d174c1.png)
![image](https://user-images.githubusercontent.com/9883910/149407850-927900c2-f088-4682-ae8d-d34e11c999a1.png)

When I click on the "Read Only" link it sends me here:
https://developer.twitter.com/en/docs/apps/app-permissions

I tried to delete my project recreate the app in another way, but there doesn't seem to be one. 
I'm pretty stuck here, not sure how I can make it read and write without using authentication as the portal is asking me to do that :s

**Comment by bramses** [comment]
@kenjibailly facing same issue!
@chhoumann what should we set as a callback url?

**Comment by kenjibailly** [comment]
> @kenjibailly facing same issue! @chhoumann what should we set as a callback url?
> 
> EDIT
> 
> I figured something out. If you apply for elevated app access and set the OAuth 1.0 settings it works. If not, you get this error:
> 
> ```
> data: "{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}↵"
> ```
> 
> For the callback url I just put it on a random server that I own, to make sure Twitter doesn't post random stuff where I can't receive it.

This worked! Thank you so much! 
I can finally send out tweets!
