### ISSUE TITLE
report a issue. (maybe need update twitter api)

### ISSUE THREAD

**Issue by skyue** [chhoumann/notetweet_obsidian#33]
I like this plugin very much. But report an issue when I use it to post tweets.

**The pop window:**

<img width="565" alt="image" src="https://user-images.githubusercontent.com/10450242/208288551-de0299ec-161f-4499-96fc-8fb7ccb4792a.png">

**The message I found in the console:**

```
"{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}
"
```

**My environment:**

MacOS 13.0.1
Obsidian 1.0.3

**Comment by Doom666** [comment]
Same here

**Comment by fred1357944** [comment]
same here :D

**Comment by ArtemisFowl-san** [comment]
Same here. Could you please give a brief update about this?

**Comment by webmasterraj** [comment]
Yes, the Twitter API needs to be updated to v2. I've opened [PR](https://github.com/chhoumann/notetweet_obsidian/pull/34) that fixes it. 

In the meantime, until it gets merged, you can use my branch. I am using it right now, and the plugin works again :).

**Comment by chhoumann** [comment]
Thanks to the PR from @webmasterraj we have a fix. I just merged it, and will make a release ASAP.
