### ISSUE TITLE
Schedule Tweets

### ISSUE THREAD

**Issue by pcuellar** [chhoumann/notetweet_obsidian#9]
I've been using this plugin heavily. One feature that would be great to have is the ability to schedule tweets. I have a page where I store all my tweets and I tend to write more than what I tweet. It would be great to be able to automate the process. Maybe this can be accomplished in combination with the templater plugin?

**Comment by chhoumann** [comment]
Sounds great! I'll see what I can do.

**Comment by chhoumann** [comment]
I didn't forget this! Don't worry. Just to give an update; I've worked on this for a bit now, and I'm getting closer to a release.

**Comment by chhoumann** [comment]
Implemented in 0.4.2. #17

**Comment by pcuellar** [comment]
This is terrific, thanks for all the work on it. I'll be testing it soon and sending you comments as I go.
